#seed: 42
#structure_config: True
tags: []

dataset:
  name: ???
  window: 12
  horizon: 12
  splitting:
    val_len: 0.1
    test_len: 0.2
  connectivity:
    method: distance
    threshold: 0.1
    include_self: False
    layout: edge_index

datamodule:
  mask_scaling: True
  workers: 0
  pin_memory: False

model: ???

training:
  batch_size: 64
  epochs: 100
  patience: 40
  grad_clip_val: 5
  optimizer:
    name: Adam
    params:
      lr: 0.001
      weight_decay: 0.0001
  scheduler:
    name: CosineAnnealingLR
    params:
      eta_min: 0.0001
      T_max: ${training.epochs}
