name: tsl-test
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.9.0
  - pytorch-lightning>=1.8,<1.9
  - torchmetrics>=0.7,<0.11
  - pyg>=2.0.3
  - pip
  - pip:
      - einops
      - hydra-core
      - numpy>1.20.3
      - omegaconf
      - pandas>=1.4,<1.5
      - PyYAML
      - scikit-learn
      - scipy
      - tables
      - tqdm
