name: tsl
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.9
  - pytorch-lightning>=1.5
  - torchmetrics>=0.7
  - pyg>=2.0
  - pip
  - pip:
      - .
      - einops
      - hydra-core
      - numpy
      - omegaconf
      - pandas
      - scikit-learn
      - scipy
      - tables
      - test-tube
      - tqdm
