name: tsl
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.9
  - pytorch-lightning>=1.5,<1.8
  - torchmetrics>=0.7,<0.11
  - pyg>=2.0.3
  - pip
  - pip:
      - .
      - einops
      - hydra-core
      - numpy
      - omegaconf
      - pandas>=1.4,<1.5
      - scikit-learn
      - scipy
      - tables
      - tqdm
