defaults:
  - default
  - _self_

model:
  name: dcrnn
  params:
    hidden_size: 64
    ff_size: 128
    kernel_size: 2
    n_layers: 1
    dropout: 0

dataset:
  connectivity:
    layout: csr

optimizer:
  params:
    lr: 0.01

lr_scheduler:
  name: MultiStepLR
  params:
    gamma: 0.1
    milestones: [ 20, 30, 40 ]