name: rtd38
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.9
  - cpuonly
  - pytorch-lightning>=1.5
  - torchmetrics>=0.7
  - pip
  - pip:
      - ..[full]
      - einops
      - numpy
      - pandas
      - scikit-learn
      - scipy
      - tables
      - test_tube
      - sphinx
      - sphinxext-opengraph
      - furo
